name: Build and deploy Next.js app to Azure Web App - Omniplix-jatin

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy necessary files for deployment
        run: |
          mkdir deploy
          cp -r .next public package.json next.config.js deploy/
          if [ -f ecosystem.config.js ]; then cp ecosystem.config.js deploy/; fi
          if [ -f server.js ]; then cp server.js deploy/; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: deploy/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_108C0CDFF97A402CAD580254DCA05B13 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AF80CD04B58D41899FCC4886835A61F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B9186CB6B7EA45EBBCD607D26D3F874F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Omniplix-jatin"
          slot-name: "Production"
          package: .
